steps:
- name: 'gcr.io/cloud-builders/gradle:5.6.2-jdk-8'
  args: ['--stacktrace', 'build']
artifacts:
  objects:
    location: 'gs://$_ARTIFACT_BUCKET/$PROJECT_ID/$BUILD_ID'
    paths: ['build/distributions/*.zip']
